### PR TITLE
Set cookies_policy cookie on client side, add fallback message if JS enabled

### PR DESCRIPTION
**Pull request by netdesignr**
Hi @AshTNA,

This is a new addition to the plugin. Due to the problems we've encountered while setting the cookie from the server-side, I think setting it at the client side will solve the issue and also still keep the progressive enhancement in place.
We're going to move all the other logic which is unsetting the cookies from the backend later on.
For the time being, we need to see if the approach I've mentioned above will help us progress with the project.

Thank you!

### CODE REVIEW

**Review by AshGDS — COMMENTED** [review]
Hi @netdesignr 

Code wise this looks OK from my perspective. However as the plugin is now JavaScript reliant it goes against our development guide, so I'll likely need @gtvj to provide his thoughts on these changes before I can merge it.

Do you have any views on this @gtvj? Thanks :+1:

**Comment by gtvj** [comment]
@netdesignr - does this mean the functionality would be JavaScript reliant? How does the approach fit with progressive enhancement (https://www.gov.uk/service-manual/technology/using-progressive-enhancement)

**Comment by netdesignr** [comment]
Hi @AshTNA and @gtvj I don't think it goes against it. Please have a play on gov.uk and see that this approach is exactly the same.

**Comment by gtvj** [comment]
@netdesignr - I've looked at the code and can't see how this is progressive enhancement because the user would be unable to change their cookie settings without JavaScript. 

Going against the Service Manual isn't something I'd take lightly - not least of all because the Cookie Consent work will be integrated into Etna which will be formally assessed against the Service Manual later this year. I'd like to understand a bit more about why it is we feel there is no other option but to go against the Service Manual.

**Comment by gtvj** [comment]
Thanks @netdesignr for explaining this in our telephone call just now. 

OK, so I now see that the proposal is for the _setting_ of all cookies (including those a user might choose to opt out of) will require JavaScript and that this is in line with what is on GOV.UK currently. On the basis that we seem to have exhausted all options for addressing the issue in the live infrastructure which is preventing cookies from being set, this seems an OK way to proceed.

**Review by AshGDS — APPROVED** [review]
Thanks @gtvj and @netdesignr - I will merge this.

**Pull request merged**
